services:
  db:
    image: postgres
    restart: always
    command: postgres -c wal_level=logical
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql
volumes:
  pgdata:
